### ISSUE TITLE
how to fake 115 brower inorder to download file?

### ISSUE THREAD

**Issue by h8spaCec4EspUdE** [zsxsoft/php-useragent#1]
I get the following user agent header with native 115 brower:
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 115Browser/5.1.5

I used it on chrome user agent switcher plugin and log in my 115 account. When I try to download files it detected me not using 115 brower and forbade me to download

Please help.

**Comment by zsxsoft** [comment]
URL?

**Comment by h8spaCec4EspUdE** [comment]
普通下载 is ok.
极速下载 or downloading a folder fails. It detects me not using 115 browser.

**Comment by zsxsoft** [comment]
I think that to install a 115 Browser is more faster than to try to crack protocols...

First, download it, and start the installion. You should remove the check that I marked.
![qq 20150217155332](https://cloud.githubusercontent.com/assets/2398785/6224832/7c0cdc4a-b6bd-11e4-860c-f7fbe22f2783.png)

After downloading your files, you can uninstall it.
![qq 20150217155503](https://cloud.githubusercontent.com/assets/2398785/6224828/7981dd5e-b6bd-11e4-84a9-c9348c4f5a27.png)

![qq 20150217155515](https://cloud.githubusercontent.com/assets/2398785/6224826/76fdbabc-b6bd-11e4-9c89-824fd9c71d79.png)

![qq 20150217155527](https://cloud.githubusercontent.com/assets/2398785/6224823/71959d06-b6bd-11e4-9710-5023163a3142.png)

By the way, here is a place to submit issues for this project, rather than a forum to discuss how to download something...

That's all.
